# File with configs for execute projects about spring batch

version: "3.8"

services:

  postgresql-11:
    image: postgres:11

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./_db:/docker-entrypoint-initdb.d/